"""Calendar runner: generates calendar preview reports."""

import json
from dataclasses import asdict
from datetime import date, datetime
from pathlib import Path

from worldcup_campaign.calendar_engine import CalendarEngine, CalendarState


class CalendarRunner:
    """Runs a calendar preview for a given date."""

    def __init__(
        self,
        policy_path: str,
        stage_map_path: str,
        match_registry_path: str,
    ):
        self.engine = CalendarEngine(
            policy_path=policy_path,
            stage_map_path=stage_map_path,
            match_registry_path=match_registry_path,
        )

    def run(self, target_date: str) -> CalendarState:
        """Run calendar preview for a given date string."""
        dt = date.fromisoformat(target_date)
        return self.engine.get_state(dt)

    def write_json_report(self, state: CalendarState, path: str) -> None:
        """Write calendar preview as JSON."""
        data = asdict(state)
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(
            json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
        )

    def write_markdown_report(self, state: CalendarState, path: str) -> None:
        """Write calendar preview as Markdown."""
        lines = []
        lines.append("# WorldCup Calendar Preview")
        lines.append("")
        lines.append("## Current Status")
        lines.append("")
        lines.append(f"- **Date:** {state.current_date}")
        lines.append(f"- **Stage:** {state.current_stage} ({state.stage_display_name})")
        lines.append(f"- **Strategy Focus:** {state.strategy_focus}")
        lines.append("")
        lines.append("## Match Counts")
        lines.append("")
        lines.append(f"- **Matches Today:** {state.matches_today_count}")
        lines.append(f"- **Matches Remaining:** {state.matches_remaining_count}")
        lines.append(f"- **Effective Windows Left:** {state.effective_windows_left}")
        lines.append("")
        
        if state.warnings:
            lines.append("## Warnings")
            lines.append("")
            for w in state.warnings:
                lines.append(f"- ⚠ {w}")
            lines.append("")

        if state.today_matches:
            lines.append("## Today's Matches")
            lines.append("")
            lines.append("| # | Match ID | Home | Away | Stage | Group | KO | Time |")
            lines.append("|---|----------|------|------|-------|-------|----|------|")
            for m in state.today_matches:
                lines.append(
                    f"| {m['match_number']} | {m['match_id']} | {m['home_team']} "
                    f"| {m['away_team']} | {m['stage']} | {m.get('group', '-')} "
                    f"| {'Y' if m['is_knockout'] else 'N'} | {m.get('kickoff_slot', '')} |"
                )
            lines.append("")

        if state.upcoming_matches:
            lines.append("## Upcoming Matches (Next 10)")
            lines.append("")
            lines.append("| Date | # | Home | Away | Stage | KO |")
            lines.append("|------|---|------|------|-------|----|")
            for m in state.upcoming_matches:
                lines.append(
                    f"| {m['date']} | {m['match_number']} | {m['home_team']} "
                    f"| {m['away_team']} | {m['stage']} "
                    f"| {'Y' if m['is_knockout'] else 'N'} |"
                )
            lines.append("")

        if state.stage_summary:
            lines.append("## Stage Summary")
            lines.append("")
            lines.append("| Stage | Dates | Matches | Focus |")
            lines.append("|-------|-------|---------|-------|")
            for s in state.stage_summary.get("stages", []):
                lines.append(
                    f"| {s['stage']} | {s['dates']} | {s['matches']} "
                    f"| {s['strategy_focus']} |"
                )
            lines.append(f"| **Total** | | **{state.stage_summary.get('total_matches_expected', 0)}** | |")
            lines.append("")

        lines.append("## Safety Boundary")
        lines.append("")
        lines.append("| Flag | Value |")
        lines.append("|------|-------|")
        for key, value in state.safety.items():
            lines.append(f"| {key} | {value} |")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by WorldCup Calendar Engine v1*")

        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text("\n".join(lines), encoding="utf-8")