"""Dashboard renderer: outputs JSON, Markdown, and static HTML."""
import json, sys
from dataclasses import asdict
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "src"))


class DashboardRenderer:
    def __init__(self, forbidden_fields: list = None):
        self.forbidden = forbidden_fields or []

    def render_json(self, dashboard) -> dict:
        return asdict(dashboard)

    def render_markdown(self, dashboard, brief) -> str:
        bs = dashboard.bankroll_summary
        cs = dashboard.calendar_summary
        ps = dashboard.parlay_summary
        fs = dashboard.futures_summary
        ss = dashboard.settlement_summary

        lines = [
            "# Campaign Dashboard",
            "",
            f"**Date:** {dashboard.current_date} | **Mode:** {dashboard.dashboard_mode}",
            "",
            "## Campaign State",
            f"- State: {bs['bankroll_state']}",
            f"- Liquid: {bs['liquid_simulated_bankroll']} CNY",
            f"- Locked Pending: {bs['locked_pending_units']} CNY",
            f"- Total Equity: {bs['total_campaign_equity']} CNY",
            f"- Target: {bs['target_bankroll']} CNY",
            f"- Multiplier (Liquid): {bs['required_multiplier_liquid']}x",
            f"- Multiplier (Equity): {bs['required_multiplier_equity']}x",
            "",
            "## Calendar",
            f"- Stage: {cs.get('stage','')} | Mode: {cs.get('daily_mode','')}",
            f"- Matches Today: {cs.get('match_count',0)} | Remaining: {cs.get('remaining_matches',0)}",
            "",
            "## Bucket Summary",
        ]
        for b, info in (dashboard.bucket_summary or {}).items():
            lines.append(f"- **{b}**: {info.get('budget',0)} CNY, {info.get('candidate_count',0)} candidates")
        lines.append("")
        lines.append("## Parlay")
        lines.append(f"- Candidates: {ps.get('source_candidates',0)} -> Combos: {ps.get('ranked_count',0)} (blocked: {ps.get('blocked_count',0)})")
        lines.append(f"- Edge: {ps.get('edge_parlays',0)} | Attack: {ps.get('attack_parlays',0)}")
        lines.append("")
        lines.append("## Futures")
        lines.append(f"- Groups: {fs.get('groups_simulated',0)} | Odds: {fs.get('futures_odds_count',0)} | Bucket: {fs.get('futures_bucket',0)}")
        lines.append("")
        lines.append("## Settlement")
        lines.append(f"- Settled: {ss.get('settled',0)} | Pending: {ss.get('pending',0)} | Hit: {ss.get('hit',0)}")
        lines.append(f"- Routing: {ss.get('routing_hint','')}")
        lines.append("")
        lines.append("## Safety")
        for k, v in dashboard.safety.items():
            lines.append(f"- **{k}:** {v}")
        lines.append("")
        lines.append("*Generated by Campaign Dashboard v1*")
        return chr(10).join(lines)

    def render_html(self, dashboard, brief) -> str:
        bs = dashboard.bankroll_summary
        cs = dashboard.calendar_summary
        ps = dashboard.parlay_summary
        fs = dashboard.futures_summary
        ss = dashboard.settlement_summary

        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><title>Campaign Dashboard</title>
<style>
body{{font-family:system-ui,sans-serif;background:#0f1923;color:#e0e0e0;margin:20px;}}
.card{{background:#1a2733;border-radius:8px;padding:16px;margin:12px 0;}}
h1{{color:#4fc3f7;}}h2{{color:#81d4fa;font-size:1.1em;}}
.metric{{font-size:1.4em;font-weight:bold;color:#4caf50;}}
.warn{{color:#ff9800;}}.danger{{color:#f44336;}}
table{{border-collapse:collapse;width:100%;}}
th,td{{padding:6px 10px;text-align:left;border-bottom:1px solid #333;}}
th{{color:#81d4fa;}}
.footer{{color:#666;font-size:0.8em;margin-top:20px;}}
</style></head>
<body>
<h1>世界杯 Campaign Dashboard</h1>
<p>{dashboard.current_date} | Mode: {dashboard.dashboard_mode}</p>

<div class="card">
<h2>Campaign State</h2>
<p>State: <span class="metric">{bs['bankroll_state']}</span></p>
<p>Liquid: <span class="metric">{bs['liquid_simulated_bankroll']} CNY</span></p>
<p>Locked Pending: <span class="warn">{bs['locked_pending_units']} CNY</span></p>
<p>Total Equity: <span class="metric">{bs['total_campaign_equity']} CNY</span></p>
<p>Multiplier: {bs['required_multiplier_liquid']}x (liquid) | {bs['required_multiplier_equity']}x (equity)</p>
</div>

<div class="card">
<h2>Calendar & Execution</h2>
<p>Stage: {cs.get('stage','')} | Mode: {cs.get('daily_mode','')} | Matches: {cs.get('match_count',0)}</p>
<p>Modules: {', '.join(dashboard.execution_schedule_summary.get('recommended_modules',[]))}</p>
</div>

<div class="card">
<h2>Bucket Summary</h2>
<table>
<tr><th>Bucket</th><th>Budget</th><th>Candidates</th><th>Role</th></tr>
{chr(10).join(f'<tr><td>{b}</td><td>{info.get("budget",0)}</td><td>{info.get("candidate_count",0)}</td><td>{info.get("role","")}</td></tr>' for b,info in (dashboard.bucket_summary or {}).items())}
</table>
</div>

<div class="card">
<h2>Parlay</h2>
<p>Source: {ps.get('source_candidates',0)} | Combos: {ps.get('ranked_count',0)} | Blocked: {ps.get('blocked_count',0)}</p>
<p>Edge: {ps.get('edge_parlays',0)} | Attack: {ps.get('attack_parlays',0)}</p>
</div>

<div class="card">
<h2>Futures</h2>
<p>Groups: {fs.get('groups_simulated',0)} | Odds: {fs.get('futures_odds_count',0)} | Bucket: {fs.get('futures_bucket',0)}</p>
<p class="warn">Winner prob sum: {fs.get('winner_prob_sum',0):.4f} (v1 simplified)</p>
</div>

<div class="card">
<h2>Settlement</h2>
<p>Settled: {ss.get('settled',0)} | Pending: {ss.get('pending',0)} | Hit: {ss.get('hit',0)}</p>
<p>Routing: {ss.get('routing_hint','')}</p>
</div>

<div class="card">
<h2>Warnings</h2>
{chr(10).join(f'<p class="warn">{w}</p>' for w in dashboard.warnings_summary[:8])}
</div>

<div class="footer">
<p>Analysis only. Simulation only. NOT betting advice. | Campaign Dashboard v1</p>
</div>
</body></html>"""

    def write_outputs(self, dashboard, brief, output_dir: str) -> dict:
        od = Path(output_dir)
        od.mkdir(parents=True, exist_ok=True)

        paths = {}
        paths["json"] = str(od / "campaign_dashboard.json")
        paths["md"] = str(od / "daily_brief.md")
        paths["html"] = str(od / "campaign_dashboard.html")

        Path(paths["json"]).write_text(json.dumps(self.render_json(dashboard), indent=2, ensure_ascii=False, default=str), encoding="utf-8")
        Path(paths["md"]).write_text(self.render_markdown(dashboard, brief), encoding="utf-8")
        Path(paths["html"]).write_text(self.render_html(dashboard, brief), encoding="utf-8")

        return paths

    def validate_no_forbidden(self, payload: dict) -> None:
        """Check for forbidden actionable fields (not safety flags)."""
        actionable_forbidden = ["stake", "stake_amount", "stake_to_match",
                               "bet_instruction", "bookmaker", "bookmaker_account",
                               "real_money_balance"]
        def check_keys(d, path=""):
            if isinstance(d, dict):
                for k, v in d.items():
                    if k in actionable_forbidden:
                        raise ValueError(f"Forbidden actionable field '{k}' found at {path}")
                    check_keys(v, f"{path}.{k}" if path else k)
        check_keys(payload, "")
